const fs = require('fs');
const path = require('path');

const geojsonPath = path.join(__dirname, '../data/portsmouth_geojson.json');
const outputPath = path.join(__dirname, '../frontend/src/lib/boundaries.ts');

const data = JSON.parse(fs.readFileSync(geojsonPath, 'utf8'));

// Decimation logic from consts.ts
function decimateRing(ring, maxVertices) {
  if (ring.length <= maxVertices) return ring;
  const step = (ring.length - 1) / (maxVertices - 1);
  const out = [];
  for (let i = 0; i < maxVertices - 1; i++) {
    out.push(ring[Math.round(i * step)]);
  }
  out.push(ring[ring.length - 1]);
  return out;
}

const MAX_RING_VERTICES = 50; // Use user's new 50 max

const PORTSEA_ALL_RINGS = data.coordinates.map(polygon => decimateRing(polygon[0], MAX_RING_VERTICES));

const largestRing = data.coordinates.reduce((largest, current) => 
  current[0].length > largest[0].length ? current : largest
)[0];
const PORTSEA_POLYGON_COORDS = decimateRing(largestRing, MAX_RING_VERTICES);

const fileContent = `// Auto-generated by scripts/generate_boundaries.js
// Extracted from data/portsmouth_geojson.json decimated to ${MAX_RING_VERTICES} vertices

export const PORTSEA_ALL_RINGS: [number, number][][] = ${JSON.stringify(PORTSEA_ALL_RINGS)};

export const PORTSEA_POLYGON_COORDS: [number, number][] = ${JSON.stringify(PORTSEA_POLYGON_COORDS)};
`;

fs.writeFileSync(outputPath, fileContent);
console.log('Successfully generated frontend/src/lib/boundaries.ts');
